# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

movies = ['One piece Film red','titanic','The Dark Knight', 'Inception']
directors = ['Goro Taniguchi','James Cameron']
descriptions = ['Los Piratas de Sombrero de Paja van a un festival de musica en la isla de Elegia a ver el concierto de Uta, una diva de enorme fama. Lo que iba a ser un concierto normal es interrumpido por una gran revelacion por parte de Luffy: Uta es hija del Emperador Pirata Shanks.','Pelicula del titanic', 'Pelicula de Batman','pelicula incepcion con Leonardo di Caprio']
anos = ['2023','1997','2008','2010']
class TestAgregardirectorypelicula():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_agregardirectorypelicula(self, movie, director, descripcion, ano):
    self.driver.get("http://localhost:8001/")
    self.driver.set_window_size(1936, 1048)
    self.driver.find_element(By.ID, ":r1:-tab-1").click()
    self.driver.find_element(By.CSS_SELECTOR, "#add-director-btn > .flex").click()
    element = self.driver.find_element(By.CSS_SELECTOR, "#add-director-btn > .flex")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.ID, "name").click()
    self.driver.find_element(By.ID, "name").send_keys(director)
    self.driver.find_element(By.CSS_SELECTOR, ".h-min > .flex").click()
    self.driver.find_element(By.ID, ":r1:-tab-0").click()
    self.driver.find_element(By.CSS_SELECTOR, "#add-movie-btn .w-16").click()
    self.driver.find_element(By.ID, "title").click()
    self.driver.find_element(By.ID, "title").send_keys(movie)
    self.driver.find_element(By.ID, "description").click()
    self.driver.find_element(By.ID, "description").send_keys(descripcion)
    self.driver.find_element(By.ID, "year").click()
    self.driver.find_element(By.ID, "year").send_keys(ano)
    self.driver.find_element(By.ID, "director_id").click()
    dropdown = self.driver.find_element(By.ID, "director_id")
    dropdown.find_element(By.XPATH, "//option[. = '"+director+"']").click()
    self.driver.find_element(By.CSS_SELECTOR, ".h-min > .flex").click()

oTest = TestAgregardirectorypelicula()
oTest.setup_method()
oTest.test_agregardirectorypelicula(movies[0],directors[0],descriptions[0],anos[0])
oTest.test_agregardirectorypelicula(movies[1],directors[1],descriptions[1],anos[1])
oTest.test_agregardirectorypelicula(movies[2],'Cristopher Nolan',descriptions[2],anos[2])
oTest.test_agregardirectorypelicula(movies[3],'Cristopher Nolan',descriptions[3],anos[3])

  
